### ISSUE TITLE
Supporting using on YAML file that contains secrets for multiple environments

### ISSUE THREAD

**Issue by tusamcalles** [nordcloud/serverless-kms-secrets#24]
It would be nice if plugins worked with one YAML file, rather than one per stage.

It would work like this:

*serverless.yml*
```yaml
custom:
  serverless-kms-secrets:
    secretsFile: kms-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml (optional)
    perStage: false # defaults to true
  kmsSecrets: ${file(kms-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml)}
```

*kms-secrets.yml*
```yaml
dev:
  secrets:
      VARIABLE_NAME: encrypted_value
  keyArn: 'arn:aws:kms:us-east-1:514209761729:key/147fa7d3-e22f-486e-b4d0-27d40aa7ae7d'
prd:
  secrets:
      VARIABLE_NAME: encrypted_value
  keyArn: 'arn:aws:kms:us-east-1:514209761729:key/147fa7d3-e22f-486e-b4d0-27d40aa7ae7d'
```

Thoughts?
